model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"

notify = ["/Users/alessiofanelli/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[features]
multi_agent = true
rmcp_client = true
js_repl = false

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.raindrop]
command = "/Users/alessiofanelli/.raindrop/bin/raindrop"
args = [ "workshop", "mcp" ]

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/alessiofanelli/.codex"
CODEX_HOME = "/Users/alessiofanelli/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "0b0d41e7a14a4903d2f95b0b3f427ed796b12c8edca2fa392a03df43997075ae"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
SKY_CUA_SERVICE_PATH = "/Users/alessiofanelli/.codex/plugins/cache/openai-bundled/computer-use/1.0.799/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."notion@openai-curated"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."vercel@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

