#!/bin/bash
# HyperReview Claude Code Hook
# This script captures Claude Code events for real-time tracking
# Generated by HyperReview

DATA_DIR="/Users/alessiofanelli/.hyperreview/hook-events"
mkdir -p "$DATA_DIR"

# Read JSON from stdin
INPUT=$(cat)

# Write event to timestamped file
TIMESTAMP=$(date +%s%N)
echo "$INPUT" > "$DATA_DIR/$TIMESTAMP.json"
